### ISSUE TITLE
Add Java sample code

### ISSUE THREAD

**Issue by ggwpez** [perun-network/perun-eth-mobile#10]
Add Java example code on how to use *prnm*. In the best case it would be a complete Android Studio project that can be imported and tested easily.  
  
Scope:  
- [ ] `Wallet` import+create Account
- [ ] `Contract` set+deploy
- [ ] `Context` cancelling
- [ ] `Channel` open+settle+send+close
- [ ] `ProposalHandler`
- [ ] `UpdateHandler`
- [ ] `Watcher`  
- [ ] App permissions
- [ ] Project file

**Comment by sebastianst** [comment]
Open question is whether we create fully functional code where we start Java threads etc or just write in a comment something like
```
// Now listen for channel proposals by starting `client.HandleChannelProposals(ProposalHandler)` in a new thread.
```

**Comment by ggwpez** [comment]
As we discussed, we want a complete Java example now. I will change the title.

**Comment by sebastianst** [comment]
It would actually be nice to write a Java CI test that executes all of the above steps. Then the CI test would be the provably working example at the same time.

There probably is a way to write CI tests for Android apps.

**Comment by ggwpez** [comment]
I pushed it to `10-java-code` instead of gdrive, github gives a better overview.  
The interesting part is [here](https://github.com/perun-network/perun-eth-mobile/blob/10-java-code/android/app/src/main/java/network/perun/app/MainActivity.java) @sebastianst.
Writing the steps down, before putting them in the `README`:  
- clone the repo
- import the android/ folder as project in Android Studio
- cd perun-eth-mobile
- gomobile bind -o android/app/prnm.aar -target=android github.com/perun-network/perun-eth-mobile/
- Run app

**Comment by sebastianst** [comment]
Looks very helpful so far.
Please copy https://github.com/github/gitignore/blob/master/Android.gitignore to the `android/` folder and check if you can ignore some more files. I spotted an `.iml` file.
I'll further investigate.

**Comment by sebastianst** [comment]
Looking at the Java code, in my opinion it would help to also offer `context.WithTimeout()` (taking an `int`, interpreted as seconds by multipying with `time.Second`s on the Go side) with prnm's API. Please then create the contexts with timeouts outside the `try` blocks and call `ctx.cancel()` in the `finally` blocks.

**Comment by ggwpez** [comment]
I will add the `.gitignore`s. As it looks like we need two.  
One `android/` and one in `android/app/` since they are not recursive…
