### ISSUE TITLE
OnChainBalance

### ISSUE THREAD

**Issue by ggwpez** [perun-network/perun-eth-mobile#16]
Create a function `OnChainBalance(*Context, *Address) (*BigInt, error)` that returns the on-chain ethereum balance for the given *address* in *wei*. See [perun-eth-demo#7](https://github.com/perun-network/perun-eth-demo/pull/7) for hints.

**Comment by ggwpez** [comment]
Since we need an ethereum backend and that is created by dialing `cfg.ETHNodeURL`, it makes more sense to have it as member function of the `Client`.  
Not really nice, but i dont see a way to do it better right now.

**Comment by sebastianst** [comment]
Yes it is polluting the API of the client, and works on a different abstraction level (using the `ethclient` just as a ChainStateReader) but is the easiest and quickest solution. If this repo becomes more broadly used, we will change it later.
