### ISSUE TITLE
Charon update

### ISSUE THREAD

**Issue by sebastianst** [perun-network/perun-eth-mobile#19]
We should update the mobile wrapper's go-perun to Charon.

This implies several changes/additions
- Expose `OnNewChannel` callback registration. Document that starting of watcher should happen here, if wanted.
- Change to and expose new common handler routine `Client.Handle`.
- Add an optional `dbpath` section to the configuration. If set, use it to enable leveldb persistence.
- Expose `Client.Reconnect(*Context)` method. Note that the `OnNewChannel` callback has to be set _before_ restoring of channels from persistence happens, or persisted channels go unnoticed and are only pollable through `Client.Channel`.
- Apply all changes to the Java example.

**Comment by ggwpez** [comment]
When trying to build the bindings, i get an error stating that:  
`prebuild constraints exclude all Go files in ~/go/pkg/mod/github.com/ethereum/go-ethereum@v1.9.14/crypto/secp256k1`  
Seems to have something to do with the new *go-ethereum* version i guess. Adding  
`CGO_ENABLED=0` as environment variable seems to fix it, but i could not test it yet.

**Comment by ggwpez** [comment]
Should we let the  `Accept` and `ProposeChannel` only return the `ID` now, since the channel should not be used anyway? @sebastianst

**Comment by sebastianst** [comment]
> Should we let the `Accept` and `ProposeChannel` only return the `ID` now, since the channel should not be used anyway? @sebastianst

This might actually be a good idea to even change in the `client.Client`'s API to prevent users from accidentally putting the returned `*Channel` in a wrapper type here and in the `OnNewChannel` callback.

**Comment by ggwpez** [comment]
Something with the persistence-reconnection is not working, will put the Persistence in an additional issue so that we can at least get the other stuff working.  
PS: See #21, #22

**Comment by sebastianst** [comment]
> Something with the persistence-reconnection is not working, will put the Persistence in an additional issue so that we can at least get the other stuff working.

Sounds good. Let's do persistence in a 2nd MR then.
