### ISSUE TITLE
Upgrade to Despina

### ISSUE THREAD

**Issue by sebastianst** [perun-network/perun-eth-mobile#27]
We did a big refactor in go-perun and moved connection handling out of the `client.Client` into a `wire/net.Bus`. The tcp/unix dialer and listener implementations were moved into `wire/net/simple`. This repo should be updated:
- [x] Inside `prnm.NewClient`, before creating the client, create a `net.Bus` with a tcp dialer and listener.
- [x] Start `Listen`ing with the `net.Bus`, not with the client.
- [x] Pass this bus to the client's constructor instead of a tcp dialer and listener, which were given to the bus before.
- [x] `Client.Reconnect` was renamed to `Restore` and the meaning of this method changed. Please also rename the method of the prnm client wrapper.
- [x] Remove `prnm.Channel.Close`

Maybe I forgot something, but this should become apparent while testing.

**Comment by ggwpez** [comment]
>Remove prnm.Channel.Close 

Why this? The bus is not closed otherwise for example.
