### ISSUE TITLE
Add means to deploy contracts

### ISSUE THREAD

**Issue by sebastianst** [perun-network/perun-eth-mobile#3]
The user of prnm needs means to deploy the `ETHAssetHolder` and `Adjudicator` contracts. It is probably easiest to directly add methods for deploying them to the `Client` type (together with `Address` setters).

What do you think @ggwpez?

**Comment by ggwpez** [comment]
I thought we do constant contracts in the mobile bindings?! They can be deployed with the demo node right now if needed.

**Comment by sebastianst** [comment]
No, phones also need to be able to deploy contracts eventually.

**Comment by ggwpez** [comment]
Ok so as Concept:  
`client.DeployAdjudicator(ctx) (*Address, error)`  
`client.DeployAssetHolder(ctx, *Address) (*Address, error)`  
`client.SetAdjudicator(*Address) error`  
`client.SetAssetHolder(*Address) error`  
(we would need contexts here too when maybe in a later version *go-perun* checks that the correct contract is deployed at that address and needs to query the blockchain)

**Comment by sebastianst** [comment]
Looks good. And yes, also add contexts to the setters, because an on-chain check should happen.

**Comment by ggwpez** [comment]
Actually we need the Contracts when creating the `client.Client` object, but the `Deploy*` methods need a `ContractBackend` (with account, wallet, eth-node) so doing it like in the *demo-node* would probably be the easiest. Either set the `Adjudicator` and `AssetHolder` addresses in the `Config`, or when not setting them they are deployed.

**Comment by sebastianst** [comment]
Hmm, I see. Sounds like a sane default for now. Please also document this for type `Config` and the contract address fields (to be added).
